apiVersion: v2
name: daytwo
description: A collection of controllers which perform work in response to a new cluster deployment.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "0.1.2"

dependencies:
- name: argocd-register-controller
  version: 0.0.24
  repository: https://lknite.github.io/charts
- name: argocd-pinniped-controller
  version: 0.0.24
  repository: https://lknite.github.io/charts
- name: argocd-labels-controller
  version: 0.0.7
  repository: https://lknite.github.io/charts
- name: argocd-kasten-controller
  version: 0.0.4
  repository: https://lknite.github.io/charts
